variables:
  AZURE_PIPELINES: true
  AZURE_BRANCH_NAME: $[ variables['Build.SourceBranch'] ]
  # Specify build author as an environment variable because on Apple Silicon
  # build_librepcb.sh is run locally where we want to use a different author.
  LIBREPCB_BUILD_AUTHOR: "LibrePCB CI"

jobs:
- template: azure-jobs-stylecheck.yml
- template: azure-jobs-doxygen.yml
- template: azure-jobs-linux.yml
- template: azure-jobs-macos.yml
- template: azure-jobs-windows.yml
